---
# These substitutions allow the end user to override certain values
substitutions:
  name: "indicator-panel"

esphome:
  name: "${name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  platformio_options:
    board_build.arduino.memory_type: qio_opi

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: esphome.project-template
    version: "1.0"

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  partitions: "default_16MB.csv"
  framework:
    type: arduino

# To be able to get logs from the device via serial and api.
logger:
  level: DEBUG

# API is a requirement of the dashboard import.
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: on

ota:
  platform: esphome

psram:
  mode: octal
  speed: 80MHz

color:
  - id: gray
    red: 50%
    green: 50%
    blue: 50%

font:
  - file: "gfonts://Roboto"
    id: web_font
    size: 20

spi:
  clk_pin: 12
  mosi_pin: 11

display:
  - platform: ili9xxx
    model: gc9a01a
    auto_clear_enabled: false
    id: gca901_display1
    invert_colors: false
    cs_pin: GPIO21 # CS1
    dc_pin:
      number: GPIO5
      allow_other_uses: true
    reset_pin:
      number: GPIO6
    dimensions:
      height: 240
      width: 240
    rotation: 90°
    data_rate: 20MHz
    lambda: |-
      it.print(50, 50, id(web_font), "kill me1!");
  - platform: ili9xxx
    model: gc9a01a
    auto_clear_enabled: false
    id: gca901_display2
    invert_colors: false
    cs_pin: GPIO48 # CS2
    dc_pin:
      number: GPIO5
      allow_other_uses: true
    dimensions:
      height: 240
      width: 240
    rotation: 90°
    data_rate: 20MHz
    lambda: |-
      it.print(50, 50, id(web_font), "kill me2!");
  - platform: ili9xxx
    model: gc9a01a
    auto_clear_enabled: false
    id: gca901_display3
    invert_colors: false
    cs_pin: GPIO18 # CS3
    dc_pin:
      number: GPIO5
      allow_other_uses: true
    dimensions:
      height: 240
      width: 240
    rotation: 90°
    data_rate: 20MHz
    lambda: |-
      it.print(50, 50, id(web_font), "kill me3!");
  - platform: ili9xxx
    model: gc9a01a
    auto_clear_enabled: false
    id: gca901_display4
    invert_colors: false
    cs_pin: GPIO17 # CS4
    dc_pin:
      number: GPIO5
      allow_other_uses: true
    dimensions:
      height: 240
      width: 240
    rotation: 90°
    data_rate: 20MHz
    lambda: |-
      it.print(50, 50, id(web_font), "kill me4!");
  - platform: ili9xxx
    model: gc9a01a
    auto_clear_enabled: false
    id: gca901_display5
    invert_colors: false
    cs_pin: GPIO38 # CS5
    dc_pin:
      number: GPIO5
      allow_other_uses: true
    dimensions:
      height: 240
      width: 240
    rotation: 90°
    data_rate: 20MHz
    lambda: |-
      it.print(50, 50, id(web_font), "kill me5!");
  - platform: ili9xxx
    model: gc9a01a
    auto_clear_enabled: false
    id: gca901_display6
    invert_colors: false
    cs_pin: GPIO45 # CS6
    dc_pin:
      number: GPIO5
      allow_other_uses: true
    dimensions:
      height: 240
      width: 240
    rotation: 90°
    data_rate: 20MHz
    lambda: |-
      it.print(50, 50, id(web_font), "kill me6!");
  - platform: ili9xxx
    model: gc9a01a
    auto_clear_enabled: false
    id: gca901_display7
    invert_colors: false
    cs_pin: GPIO46 # CS7
    dc_pin:
      number: GPIO5
      allow_other_uses: true
    dimensions:
      height: 240
      width: 240
    rotation: 90°
    data_rate: 20MHz
    lambda: |-
      it.print(50, 50, id(web_font), "kill me7!");
  - platform: ili9xxx
    model: gc9a01a
    auto_clear_enabled: false
    id: gca901_display8
    invert_colors: false
    cs_pin: GPIO47 # CS8
    dc_pin:
      number: GPIO5
      allow_other_uses: true
    dimensions:
      height: 240
      width: 240
    rotation: 90°
    data_rate: 20MHz
    lambda: |-
      it.print(50, 50, id(web_font), "kill me8!");
#  - platform: ili9xxx
#    model: gc9a01a
#    auto_clear_enabled: false
#    id: gca901_display9
#    cs_pin: GPIO18  # CS9
#    dc_pin:
#      number: GPIO5
#      allow_other_uses: true
#    dimensions:
#      height: 240
#      width: 240
#    rotation: 90°
#    data_rate: 20MHz
#    lambda: |-
#      it.print(50, 50, id(web_font), "kill me9!");

output:
  - id: led_1_output
    platform: gpio
    pin: GPIO3
  - id: led_2_output
    platform: gpio
    pin: GPIO15
  - id: led_3_output
    platform: gpio
    pin: GPIO13
  - id: led_4_output
    platform: gpio
    pin: GPIO10
  - id: led_5_output
    platform: gpio
    pin: GPIO9
  - id: led_6_output
    platform: gpio
    pin: GPIO8
  - id: led_7_output
    platform: gpio
    pin: GPIO7
  - id: led_8_output
    platform: gpio
    pin: GPIO4

light:
  - platform: binary
    id: led_1
    name: led_1
    restore_mode: ALWAYS_ON
    output: led_1_output
  - platform: binary
    id: led_2
    name: led_2
    restore_mode: ALWAYS_ON
    output: led_2_output
  - platform: binary
    id: led_3
    name: led_3
    restore_mode: ALWAYS_ON
    output: led_3_output
  - platform: binary
    id: led_4
    name: led_4
    restore_mode: ALWAYS_ON
    output: led_4_output
  - platform: binary
    id: led_5
    name: led_5
    restore_mode: ALWAYS_ON
    output: led_5_output
  - platform: binary
    id: led_6
    name: led_6
    restore_mode: ALWAYS_ON
    output: led_6_output
  - platform: binary
    id: led_7
    name: led_7
    restore_mode: ALWAYS_ON
    output: led_7_output
  - platform: binary
    id: led_8
    name: led_8
    restore_mode: ALWAYS_ON
    output: led_8_output
